In [ ]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
import pandas as pd
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Reading the metadata files
with open("car.c45-names", "r") as c45_file:
    c45_content = c45_file.read()

with open("car.names", "r") as names_file:
    names_content = names_file.read()

In [ ]:
# Printing out the content of the metadata files
print("C4.5 Names Content:\n", c45_content)
print("\nNames File Content:\n", names_content)

C4.5 Names Content:
 | names file (C4.5 format) for car evaluation domain

| class values

unacc, acc, good, vgood

| attributes

buying:   vhigh, high, med, low.
maint:    vhigh, high, med, low.
doors:    2, 3, 4, 5more.
persons:  2, 4, more.
lug_boot: small, med, big.
safety:   low, med, high.


Names File Content:
 1. Title: Car Evaluation Database

2. Sources:
   (a) Creator: Marko Bohanec
   (b) Donors: Marko Bohanec   (marko.bohanec@ijs.si)
               Blaz Zupan      (blaz.zupan@ijs.si)
   (c) Date: June, 1997

3. Past Usage:

   The hierarchical decision model, from which this dataset is
   derived, was first presented in 

   M. Bohanec and V. Rajkovic: Knowledge acquisition and explanation for
   multi-attribute decision making. In 8th Intl Workshop on Expert
   Systems and their Applications, Avignon, France. pages 59-78, 1988.

   Within machine-learning, this dataset was used for the evaluation
   of HINT (Hierarchy INduction Tool), which was proved to be able to
   com

In [ ]:
# Reading the data file
column_names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
car_data = pd.read_csv("car.data", names=column_names)

In [ ]:
car_data.dropna(how="all",axis=1,inplace=True)
car_data

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
car_data.dropna(how="all",axis=0,inplace=True)
car_data

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
car_data=car_data.drop_duplicates()
car_data

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
# Displaying the first few rows
print("\nCar Data:\n", car_data.head())


Car Data:
   buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [ ]:
car_data.describe()

buying  maint doors persons lug_boot safety  class
count    1728   1728  1728    1728     1728   1728   1728
unique      4      4     4       3        3      3      4
top     vhigh  vhigh     2       2    small    low  unacc
freq      432    432   432     576      576    576   1210

In [ ]:
# Shuffle the dataset for randomness
car_data = shuffle(car_data, random_state=42).reset_index(drop=True)

In [ ]:
le=LabelEncoder()

In [ ]:
# Applying LabelEncoder on categorical columns
# car_data['buying'] = le.fit_transform(car_data['buying'])
# car_data['maint'] = le.fit_transform(car_data['maint'])
# car_data['doors'] = le.fit_transform(car_data['doors'])
# car_data['persons'] = le.fit_transform(car_data['persons'])
# car_data['lug_boot'] = le.fit_transform(car_data['lug_boot'])
# car_data['safety'] = le.fit_transform(car_data['safety'])
# car_data['class'] = le.fit_transform(car_data['class'])

In [ ]:
# car_data

In [ ]:
# feature_columns=["buying","maint","doors","persons","lug_boot","safety"]

In [ ]:
# X=car_data[feature_columns]
# X

In [ ]:
# feature_target=['class']
# y=car_data[feature_target]

In [ ]:
# y

In [ ]:
# Separate features (X) and labels (y)
X = car_data.drop(columns="class")
y = car_data["class"]

In [ ]:
# Calculate split indices
train_end = int(0.7 * len(X))
val_end = int(0.85 * len(X))

# Split the data into train, validation, and test sets
X_train, y_train = X[:train_end], y[:train_end]
X_val, y_val = X[train_end:val_end], y[train_end:val_end]
X_test, y_test = X[val_end:], y[val_end:]

In [ ]:
# Display shapes to verify
print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_val:", X_val.shape, "y_val:", y_val.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)

X_train: (1209, 6) y_train: (1209,)
X_val: (259, 6) y_val: (259,)
X_test: (260, 6) y_test: (260,)


In [ ]:
# Encode categorical features and labels
label_encoders = {col: LabelEncoder() for col in X_train.columns}

# Transform X
for col in X_train.columns:
    X_train[col] = label_encoders[col].fit_transform(X_train[col])
    X_val[col] = label_encoders[col].transform(X_val[col])
    X_test[col] = label_encoders[col].transform(X_test[col])

# Encode y
y_encoder = LabelEncoder()
y_train = y_encoder.fit_transform(y_train)
y_val = y_encoder.transform(y_val)
y_test = y_encoder.transform(y_test)


<ipython-input-16-cbe3531b16e0>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = label_encoders[col].fit_transform(X_train[col])
<ipython-input-16-cbe3531b16e0>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_val[col] = label_encoders[col].transform(X_val[col])
<ipython-input-16-cbe3531b16e0>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pa

In [ ]:
X_train

buying  maint  doors  persons  lug_boot  safety
0          0      0      2        0         1       0
1          2      1      0        1         1       2
2          0      0      3        0         0       2
3          1      0      3        1         1       2
4          2      1      2        2         1       1
...      ...    ...    ...      ...       ...     ...
1204       0      2      3        2         0       1
1205       0      3      2        1         1       1
1206       3      3      0        1         2       0
1207       3      1      2        2         2       1
1208       3      2      2        1         1       0

[1209 rows x 6 columns]

In [ ]:
y_train

array([2, 0, 2, ..., 2, 2, 0])

###Decision Tree

In [ ]:
model=DecisionTreeClassifier(criterion='entropy')

In [ ]:
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
# Predict on validation set
y_val_pred = model.predict(X_val)
# val_accuracy = accuracy_score(y_val, y_val_pred)

In [ ]:
# Predict on test set (optional final evaluation)
y_test_pred = model.predict(X_test)
# test_accuracy = accuracy_score(y_test, y_test_pred)

In [ ]:
y_test_pred.shape

(260,)

In [ ]:
y_test.shape

(260,)

In [ ]:
y_test.size

260

In [ ]:
y_test=y_test.squeeze()
y_test.shape

(260,)

In [ ]:
y_val=y_val.squeeze()
y_val.shape

(259,)

In [ ]:
print(type(y_test))
print(type(y_test_pred))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Accuracy with validation set
correct_predictions = np.sum(y_val_pred == y_val)
total_predictions = y_val.shape[0]  # Total number of actual classes

accuracy = correct_predictions / total_predictions
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 98.84%


In [ ]:
# Accuracy with test set
correct_predictions = np.sum(y_test_pred == y_test)
total_predictions = y_test.shape[0]  # Total number of actual classes

accuracy = correct_predictions / total_predictions
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 97.31%


In [ ]:
def true_positive(test,pred):
  tp_a,tp_b,tp_c,tp_d=0,0,0,0


  for i in range(test.size):
        if test[i] == 0 and pred[i] == 0:
            tp_a += 1
        elif test[i] == 1 and pred[i] == 1:
            tp_b += 1
        elif test[i] == 2 and pred[i] == 2:
            tp_c += 1
        elif test[i] == 3 and pred[i] == 3:
            tp_d += 1




  return tp_a,tp_b,tp_c,tp_d


In [ ]:
tp_a,tp_b,tp_c,tp_d=true_positive(y_test,y_test_pred)

In [ ]:
tp_a,tp_b,tp_c,tp_d

(65, 11, 166, 11)

In [ ]:
true_positives = np.sum((y_test_pred == 2) & (y_test == 2))
true_positives

166

In [ ]:
def false_positive(test,pred):
  fp_a,fp_b,fp_c,fp_d=0,0,0,0

  for i in range(test.size):
     if(pred[i]==0 and test[i]!=0):
       fp_a+=1
     if(pred[i]==1 and test[i]!=1):
       fp_b+=1
     if(pred[i]==2 and test[i]!=2):
       fp_c+=1
     if(pred[i]==3 and test[i]!=3):
       fp_d+=1


  return fp_a,fp_b,fp_c,fp_d


In [ ]:
fp_a,fp_b,fp_c,fp_d=false_positive(y_test,y_test_pred)
fp_a,fp_b,fp_c,fp_d

(5, 2, 0, 0)

In [ ]:
np.sum((y_test_pred == 0) & (y_test != 0))

5

In [ ]:
def false_negative(test,pred):
  fn_a,fn_b,fn_c,fn_d=0,0,0,0

  for i in range(test.size):
     if(pred[i]!=0 and test[i]==0):
       fn_a+=1
     if(pred[i]!=1 and test[i]==1):
       fn_b+=1
     if(pred[i]!=2 and test[i]==2):
       fn_c+=1
     if(pred[i]!=3 and test[i]==3):
       fn_d+=1



  return fn_a,fn_b,fn_c,fn_d


In [ ]:
fn_a,fn_b,fn_c,fn_d=false_negative(y_test_pred,y_test)
fn_a,fn_b,fn_c,fn_d

(5, 2, 0, 0)

In [ ]:
np.sum((y_test_pred == 1) & (y_test != 1))

2

In [ ]:
def true_negative(test,pred):
  tn_a,tn_b,tn_c,tn_d=0,0,0,0

  for i in range(test.size):
     if(pred[i]!=0 and test[i]!=0):
       tn_a+=1
     if(pred[i]!=1 and test[i]!=1):
       tn_b+=1
     if(pred[i]!=2 and test[i]!=2):
       tn_c+=1
     if(pred[i]!=3 and test[i]!=3):
       tn_d+=1


  return tn_a,tn_b,tn_c,tn_d

In [ ]:
tn_a,tn_b,tn_c,tn_d=true_negative(y_test_pred,y_test)
tn_a,tn_b,tn_c,tn_d

(190, 244, 92, 247)

In [ ]:
np.sum((y_test_pred != 1) & (y_test != 1))

244

In [ ]:
# Construct the OvR confusion matrices for each class
confusion_matrix_a = np.array([[tp_a, fn_a], [fp_a, tn_a]])
confusion_matrix_b = np.array([[tp_b, fn_b], [fp_b, tn_b]])
confusion_matrix_c = np.array([[tp_c, fn_c], [fp_c, tn_c]])
confusion_matrix_d = np.array([[tp_d, fn_d], [fp_d, tn_d]])

In [ ]:
confusion_matrix_a

array([[ 65,   5],
       [  5, 190]])

In [ ]:
precision_a=tp_a/(tp_a+fp_a)
precision_b=tp_b/(tp_b+fp_b)
precision_c=tp_c/(tp_c+fp_c)
precision_d=tp_d/(tp_d+fp_d)

In [ ]:
avg_precision=(precision_a+precision_b+precision_c+precision_d)/4
avg_precision

0.9436813186813187

In [ ]:
recall_a=tp_a/(tp_a+fn_a)
recall_b=tp_b/(tp_b+fn_b)
recall_c=tp_c/(tp_c+fn_c)
recall_d=tp_d/(tp_d+fn_d)

In [ ]:
avg_recall=(recall_a+recall_b+recall_c+recall_d)/4
avg_recall

0.9436813186813187

In [ ]:
fscore_a=(2*recall_a*precision_a)/(recall_a+precision_a)
fscore_b=(2*recall_b*precision_b)/(recall_b+precision_b)
fscore_c=(2*recall_c*precision_c)/(recall_c+precision_c)
fscore_d=(2*recall_d*precision_d)/(recall_d+precision_d)

In [ ]:
avg_f1_score=(fscore_a+fscore_b+fscore_c+fscore_d)/4
avg_f1_score

0.9436813186813187

###XGBoost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
model1=XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
model1.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [01:12:29] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
# Predict with XGBoost
y_test_pred1 = model1.predict(X_test)

In [ ]:
print(type(y_test))
print(type(y_test_pred1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Accuracy with test set
correct_predictions = np.sum(y_test_pred1 == y_test)
total_predictions = y_test.shape[0]  # Total number of actual classes

accuracy = correct_predictions / total_predictions
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 98.85%


In [ ]:
tp_a1,tp_b1,tp_c1,tp_d1=true_positive(y_test,y_test_pred1)
fp_a1,fp_b1,fp_c1,fp_d1=false_positive(y_test,y_test_pred1)
fn_a1,fn_b1,fn_c1,fn_d1=false_negative(y_test,y_test_pred1)
tn_a1,tn_b1,tn_c1,tn_d1=true_negative(y_test,y_test_pred1)

In [ ]:
tp_a1,tp_b1,tp_c1,tp_d1

(65, 13, 168, 11)

In [ ]:
fp_a1,fp_b1,fp_c1,fp_d1

(2, 1, 0, 0)

In [ ]:
fn_a1,fn_b1,fn_c1,fn_d1

(0, 1, 0, 2)

In [ ]:
tn_a1,tn_b1,tn_c1,tn_d1

(193, 245, 92, 247)

In [ ]:
# Construct the OvR confusion matrices for each class
confusion_matrix_a1 = np.array([[tp_a1, fn_a1], [fp_a1, tn_a1]])
confusion_matrix_b1 = np.array([[tp_b1, fn_b1], [fp_b1, tn_b1]])
confusion_matrix_c1 = np.array([[tp_c1, fn_c1], [fp_c1, tn_c1]])
confusion_matrix_d1 = np.array([[tp_d1, fn_d1], [fp_d1, tn_d1]])

In [ ]:
confusion_matrix_a1

array([[ 65,   0],
       [  2, 193]])

In [ ]:
confusion_matrix_b1

array([[ 13,   1],
       [  1, 245]])

In [ ]:
confusion_matrix_c1

array([[168,   0],
       [  0,  92]])

In [ ]:
confusion_matrix_d1

array([[ 11,   2],
       [  0, 247]])

In [ ]:
precision_a1=tp_a1/(tp_a1+fp_a1)
precision_b1=tp_b1/(tp_b1+fp_b1)
precision_c1=tp_c1/(tp_c1+fp_c1)
precision_d1=tp_d1/(tp_d1+fp_d1)

In [ ]:
avg_precision1=(precision_a1+precision_b1+precision_c1+precision_d1)/4
avg_precision1

0.974680170575693

In [ ]:
recall_a1=tp_a1/(tp_a1+fn_a1)
recall_b1=tp_b1/(tp_b1+fn_b1)
recall_c1=tp_c1/(tp_c1+fn_c1)
recall_d1=tp_d1/(tp_d1+fn_d1)

In [ ]:
avg_recall1=(recall_a1+recall_b1+recall_c1+recall_d1)/4
avg_recall1

0.9436813186813188

In [ ]:
fscore_a1=(2*recall_a1*precision_a1)/(recall_a1+precision_a1)
fscore_b1=(2*recall_b1*precision_b1)/(recall_b1+precision_b1)
fscore_c1=(2*recall_c1*precision_c1)/(recall_c1+precision_c1)
fscore_d1=(2*recall_d1*precision_d1)/(recall_d1+precision_d1)

In [ ]:
avg_f1_score1=(fscore_a1+fscore_b1+fscore_c1+fscore_d1)/4
avg_f1_score1

0.9575216450216449